apiVersion: v1
kind: Secret

metadata:
  name: chandigarh-secret

type: Opaque

stringData:
  api-key: "c05de899bcc53df9d2202b1179870c28"

  smtp-user: "manjotsingh77400@gmail.com"

  smtp-pass: "jmgr yplr zntv sxhy"
